[package]
name = "notrust-track"
version = "0.1.0"
authors = ["Alex Lisle <alex.lisle@gmail.com>"]
license-file = "LICENSE"

[dependencies]
crslmnl = "0.2"
libc = "0.2"
log = "0.4"
simple_logger = "0.5"
users = "0.7"
procfs = "0.3"
clap = "^2.3"
syslog = "^4.0"
sys-info = "*"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "^0.8"

tempfile = "^3"
