[package]
name = "notrust-track"
version = "0.1.0"
authors = ["Alex Lisle <alex.lisle@gmail.com>"]
license = "Apache-2.0"
license-file = "LICENSE"

[dependencies]
crslmnl = "0.2"
libc = "0.2"
log = "0.4"
simple_logger = "0.5"
users = "0.7"
procfs = "0.3"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
