---
# Give a name to this machine, if none is set a random one is given.
# name:

# Give a UUID for this machine, if none is set a random UUID is given.
# uuid:

# Data directory
directory: /usr/share/zerotrust
outputs:
  syslog:
    - Localhost
#    - TCP:
#        address: 127.0.0.1
#        port: 601
#    - UDP:
#        address: 127.0.0.1
#        port: 514
#  elasticsearch: "http://<ES Server>:9200/<Index>"
#  zerotrust_endpoint: "http://<zerotrust Server>

filters:
  # If this is set to true it will include all connections, including multicast
  non_process_connections: true

  # If this is set to true we show connections to and from 53 and 5353, normally this generates
  # alot of noise.
  dns_requests : true

  # If this is enabled then we will report when zerotrust-track makes an outbound connection, if you're
  # using an output which isn't local, this can create a loop of reporting.
  zerotrust_track_connections: true
